url: https://limit-dne.github.io
baseurl: /SCubed/

# Site settings
title: S Cubed Coaching
email: t.rogers.bath@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Melody Morris
  pic: 1
  position: Toby is great and I would highly recommend him as a personal trainer. He has helped me achieve my goals with weight training, cardio work and nutrition advice. I'm really happy with the service that he has provided and we review my goals regularly so that he can adapt my personalised programme to suit me. The workouts change frequently too so I am always doing new exercises and improving in the areas that I choose. Toby is friendly and very encouraging. Thanks Toby!
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Tom Manners
  pic: 2
  position: I started working with Toby a year ago and am really pleased with the results. I'm in the best shape I have been in for years! I always thought i knew a good number of exercises but Toby has helped me increase my own knowledge with a carefully planned/sequenced range of activities...and with it, also increased my own strength and conditioning! I highly recommend him! He is also a lovely guy!
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Isabelle Mantella
  pic: 3
  position: he's developed for me have been highly personalised taking into account my strength and fitness goals, previous injuries and current capabilities. During sessions he really focuses on form and execution and I've learnt a lot. It's that attention to detail that sets him apart from other Trainers I've worked with. You won't find him spending sessions looking at his phone or wasting time; you get 100% of his attention. I would highly recommend him.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
